### PR TITLE
[WIP] Hlt vertex reports

### PR DESCRIPTION
**Pull request by dpiparo**
First attempt to get the decoding of vertices done. The data structure chosen to represent the vertices in memory is a simple SOA, as discussed.
The problem encountered lies in the interpretation of the bank body.
The description provided by Rosen is:
```
- (uint32) the number of "selections" (there can be different types of PVs, but normally this should be 1)
  - for each selection:
    - (uint16) number of PVs
    - (uint16) "selection" ID
    - for each PV:
      - (float) x, (float) y, (float) z,  (float) chi2,  (uint32) ndof, (float) cov[0][0], (float) cov[1][1], (float) cov[2][2], (float) cov[0][1], (float) cov[0][2], (float) cov[1][2]
```
On the other hand, this is what we see for a bank with a single vertex (every bunch of numbers is a `char` printed with `std::hex`):
```
// 10000000 00000000 00000000 00000000         selections

// 10000000 00000000 11900000 39000000         nvtx / selID

// 4294967213 51000000 67000000 63000000       x
// 93000000 35000000 4294967189 4294967229     y
// 4294967175 4294967276 4294967173 4294967232 z

// 44000000 4294967276 10000000 66000000       chi2
// 12300000 00000000 00000000 00000000         ndof

// 11500000 12700000 4294967202 56000000       cov_00
// 72000000 4294967173 4294967182 56000000     cov_11
// 4294967251 4294967203 18000000 59000000     cov_22
// 11700000 86000000 64000000 53000000         cov_01
// 77000000 90000000 22000000 4294967225       cov_02
// 10500000 18000000 88000000 4294967223       cov_12
```
Something is not consistent. There are some points to clarify.

### CODE REVIEW

**Comment by bluehood** [comment]
Hi, out-of-source builds are broken, can you add the two new header files to the `add_library` line in `src/CMakeLists.txt`?

**Review by eguiraud — APPROVED** [review]
First decoder of many :)

**Comment by bluehood** [comment]
Rebased and merged by command line, although github does not see it 🤷‍♂️

**Comment by dpiparo** [comment]
great structure, the decoder was the cherry on top of a lot of solid work.

**Pull request closed without merging**
